version: "3.1"

services:
  app:
    build: .
    image: chatroom-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
      - migrate
    restart:
      on-failure
    networks:
      new:
        aliases:
          - app

  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_DB: chatroom
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432/tcp"
    networks:
      new:
        aliases:
          - db

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      new:
        aliases:
          - rabbitmq

  migrate:
    image: migrate/migrate
    networks:
      new:
        aliases:
          - migrate
    volumes:
      - ./migrations:/migrations
    command: >
      -path=/migrations -database "postgresql://user:password@db:5432/chatroom?sslmode=disable" up
    restart:
      on-failure
    links:
      - db

networks:
  new: