version: "3.1"

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_DB: chatroom
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 10
