APP_NAME: chatroom
APP_PORT: 8080
LOG_LEVEL: "info"
DB_MAX_IDLE_CONNS: 10
DB_MAX_OPEN_CONNS: 0
DB_MAX_LIFE_TIME: 1m
DB_MAX_IDLE_TIME: 10m
#DB_HOST: localhost
DB_HOST: db
DB_PORT: 5432
DB_NAME: chatroom
DB_USER: user
DB_PASSWORD: password
DB_SSL_MODE: disable
JWT_KEY: "secret"
STOCK_BOT_QUEUE_NAME: "stock_bot"
STOCK_BOT_TEMPLATE_URL: "https://stooq.com/q/l/?s=%s&f=sd2t2ohlcv&h&e=csv"
RABBITMQ_HOST: "rabbitmq"
RABBITMQ_HOST_TEMPLATE: "amqp://%s:%s@%s:%s"
RABBITMQ_PORT: 5672
RABBITMQ_QUEUE_NAME: "stock_bot"
RABBITMQ_USER: guest
RABBITMQ_PASS: guest