APP_NAME: chatroom
APP_PORT: 8080
LOG_LEVEL: "info"
DB_MAX_IDLE_CONNS: 10
DB_MAX_OPEN_CONNS: 0
DB_MAX_LIFE_TIME: 1m
DB_MAX_IDLE_TIME: 10m
DB_HOST: ${DB_HOST}
DB_PORT: ${DB_PORT}
DB_NAME: chatroom
DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASS}
DB_SSL_MODE: ${DB_SSL_MODE}
JWT_KEY: ${JWT_KEY}
STOCK_BOT_TEMPLATE_URL: "https://stooq.com/q/l/?s=%s&f=sd2t2ohlcv&h&e=csv"