default: &default
  APP_NAME: chatroom
  LOG_LEVEL: "info"
  PORT: 8080
  DB_MAX_IDLE_CONNS: 10
  DB_MAX_OPEN_CONNS: 0
  DB_MAX_LIFE_TIME: 1m
  DB_MAX_IDLE_TIME: 10m

dev:
  <<: *default
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: chatroom-dev
  DB_USER: user
  DB_PASSWORD: password

stg:
  <<: *default
  DB_HOST: DB_HOST_STG
  DB_PORT: DB_PORT_STG
  DB_NAME: chatroom-stg
  DB_USER: DB_USER_STG
  DB_PASSWORD: DB_PASS_STG

prd:
  <<: *default
  DB_HOST: DB_HOST_PRD
  DB_PORT: DB_PORT_PRD
  DB_NAME: chatroom-prd
  DB_USER: DB_USER_PRD
  DB_PASSWORD: DB_PASS_PRD